spring.application.name=foodiesapi

#mongodb configuration
spring.data.mongodb.uri=mongodb://admin:password@localhost:27017/foodies?authSource=admin

#aws s3 configuration
cloud.aws.credentials.access-key=
cloud.aws.credentials.secret-key=

cloud.aws.region.static=us-east-1
aws.bucket.name=food-order-service-ucmo

jwt.secret.key=

#razorpay configuration
#razorpay_key=${RAZORPAY_KEY}
#razorpay_secret=${RAZORPAY_SECRET}

razorpay_key=
razorpay_secret=g