spring.application.name=foodiesapi
#port 8080

#mongodb configuration
#spring.data.mongodb.uri=mongodb://admin:password123@localhost:27017/foodies?authSource=admin
spring.data.mongodb.uri=mongodb://subarnagaine_db_user:XZ0nzXXXXXXXXX@ac-brao4qf-shard-00-00.q0hdtp8.mongodb.net:27017,ac-brao4qf-shard-00-01.q0hdtp8.mongodb.net:27017,ac-brao4qf-shard-00-02.q0hdtp8.mongodb.net:27017/foodies?ssl=true&replicaSet=atlas-ntf0tw-shard-0&authSource=admin&appName=Cluster0

#aws s3 configuration
cloud.aws.credentials.access-key=AKIAXXXXXXXXXXXXXX
cloud.aws.credentials.secret-key=qpSnzUXXXXXXXXXXXXX4S4HRb4

cloud.aws.region.static=us-east-1
aws.bucket.name=food-order-service-ucmo

jwt.secret.key=5qY6LCcEwlXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxmWAXnOHOXrm

#cors configuration
cors.allowed.origins=http://localhost:5173,http://localhost:5174,https://on-a0a08517ed9d40d1991c282425946c16.ecs.us-east-1.on.aws,http://on-a0a08517ed9d40d1991c282425946c16.ecs.us-east-1.on.aws

#enable the below when you have your keys
stripe.secret.key=sk_test_51TQsNBAMaEUYoNhxN52mLZXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXG009fFsrKdG
stripe.public.key=pk_test_51TQsNBAMaEUYoNhxKE827tjXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXkhp5BAORZt

